# Generated by Django 5.2 on 2025-04-11 04:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monografia',
            name='arquivo',
        ),
        migrations.CreateModel(
            name='ArquivoMonografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='monografias/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx'])], verbose_name='Arquivo (PDF, Word ou PowerPoint)')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do arquivo')),
                ('monografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='gerenciador.monografia')),
            ],
            options={
                'verbose_name': 'Arquivo de Monografia',
                'verbose_name_plural': 'Arquivos de Monografia',
            },
        ),
    ]
