# Generated by Django 5.2 on 2025-04-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0002_remove_monografia_arquivo_arquivomonografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monografia',
            name='coorientador',
            field=models.CharField(max_length=255, verbose_name='Coorientador'),
        ),
    ]
